"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[manager]
prepend_keymap = [
  { on = "f", run = "search rg", desc = "Search files by content via ripgrep." },
  { on = "/", run = "filter --smart", desc = "Filter files." },
  { on = ["<C-s>"], run = ["hidden toggle"], desc = "Toggle the visibility of hidden files." },
  { on = ["l"], run = ["plugin smart-enter --sync", "escape --visual --select"], desc = "Enter the child directory, or open file." },
  { on = ["L"], run = ["plugin smart-enter --sync --args='detatch'"], desc = "Open in new window." },
  { on = ["="], run = """shell 'printf "Permissions (in mode-bits): "; read ans; chmod $ans "$@"' --block --confirm""", desc = "chmod wrapper." },
  { on = ["S"], run = """shell 'curl -F "file=@$@" -Fsecret= 0x0.st | qrencode -o "/tmp/qrcode.png" && notify-send -a "Share" -t 0 -i "/tmp/qrcode.png" " File piped to the QR code." && rm -f "/tmp/qrcode.png"' --confirm""", desc = "Share file via QR code." },
  { on = ["Z"], run = "plugin compress", desc = "Archive selected files." },
]
