command_key = ";"
use_nerdfont = true
flip_status_indicators = true
volnorm = true
notify = true
repeat = "playlist"

[theme]
primary = "#d8dee9"
secondary = "light black"
title = "#88c0d0"
playing = "#8fbcbb"
playing_selected = "#8fbcbb"
playing_bg = "black"
highlight = "#d8dee9"
highlight_bg = "#2e3440"
error = "#d8dee9"
error_bg = "red"
statusbar = "black"
statusbar_progress = "#5e81ac"
statusbar_bg = "#5e81ac"
cmdline = "#d8dee9"
cmdline_bg = "black"
search_match = "light red"

[keybindings]
"1" = "focus queue"
"2" = "focus library"
"q" = "back"
"gg" = "move top"
"G" = "move bottom"
"Space" = "playpause"
"n" = "next"
"p" = "previous"
"Q" = "queue"
"s" = "shuffle"
